### ISSUE TITLE
Waiting for React to connect (but redux works)

### ISSUE THREAD

**Issue by danieljvdm** [jhen0409/react-native-debugger#115]
Hi,

I'm getting the common 'Waiting for React to connect' bug and have tried the fixes previously mentioned in other issues. It seems like the debugger **is** connecting to the device, as my redux dev tools work, but it just won't connect to React.

It was working yesterday and even after reverts in git it's still broken.

React Native Debugger version: 0.7.3
React Native version:  47.0
Platform: IOS
Is real device of platform: Yes, but simulator also broken
Operating System: macOS

**Comment by jhen0409** [comment]
If RNDebugger still showing `Waiting for React to connect`, it's meaning your app haven't try to connect React DevTools server, you can check [this file from `react-native`](https://github.com/facebook/react-native/blob/master/Libraries/Core/Devtools/setupDevtools.js).

For real device please ensure you have read [`How to use it with real device?`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/react-devtools-integration.md#how-to-use-it-with-real-device) section of `react-devtools-integration.md`. For iOS simulator I have never failed to connect, so you need to check if you do something wrong.

**Comment by danieljvdm** [comment]
Yes I've seen that doc. It was working fine on simulator and device and has randomly stopped working.

**Comment by srounce** [comment]
Can confirm this on latest 0.7.4 too.

**Comment by jhen0409** [comment]
I'm not sure if it's related to [this change](https://github.com/facebook/react-native/commit/a93b7a2da0849f15708afef1ff99022d8cc55b14#diff-8a2d58614a696a381ddeeba0f0dc691b), it's only one change recently, but it actually works for me. Or you can try [`v0.7.2`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.7.2) for downgrade `react-devtools-core` to v2.4

**Comment by alexey-kuznetsov** [comment]
Can confirm this. But this bug appears only in physical device. In emulator all works properly.

**Comment by jhen0409** [comment]
> Can confirm this. But this bug appears only in physical device. In emulator all works properly.

@alexey-kuznetsov It should impossible if you have read [`How to use it with real device?`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/react-devtools-integration.md#how-to-use-it-with-real-device) section and ensure no any connection problems in your case. It just a websocket connection.

The main point is `iOS simulator also broken` for this issue let me confused. 🤔

Actually this issue may not related here, we just listen [a random port](https://github.com/jhen0409/react-native-debugger/blob/master/docs/react-devtools-integration.md#react-devtools-integration) and set `__REACT_DEVTOOLS_PORT__` to RN env (and [default theme setup](https://github.com/jhen0409/react-native-debugger/blob/master/app/containers/ReactInspector.js#L47)), otherwise it have no different from [`react-devtools-core`](https://github.com/facebook/react-devtools/tree/master/packages/react-devtools-core). We can debug [`setupDevtools.js `](https://github.com/facebook/react-native/blob/master/Libraries/Core/Devtools/setupDevtools.js) of RN to tracking the issue, currently I can't to help because the problem can't reproduce for me.

**Comment by alexey-kuznetsov** [comment]
@jhen0409 thank you! This solution solved my problem!

**Comment by rix1** [comment]
I had a similar problem, where both react-devtools and RND was was showing `"Waiting for React to connect"`.

Forgot that I had connected to packager over WiFi 🤦‍♂️, so connecting the physical Android device to my machine via USB solved the problem 👍

**Comment by jhen0409** [comment]
Maybe we could add some tips in UI to avoid such misunderstanding.

**Comment by Lineakat** [comment]
Does anyone know what to do, if I cant enable it in expo? It just says 'Remote debugger unavailable', see the picture. 
This is on a iPhone simulator running on my mac. 

The redux and console stuff works, but it just says 'waiting for react to connect...' in the react part. It worked yesterday, and I have tried to go back in git to a place where I know it worked, but it doesn't solve my problem. I even switched branch to a brach that works on my co-workers computer, and this it not the issue. 
A couple of times I've also gotten a 'Runtime is not ready for debugging. Make sure packager server is running'-error with a red screen on my simulator, but it only appears sometimes. 

Does anybody know what I am doing wrong? :) 

<img width="338" alt="screen shot 2018-05-24 at 11 52 10" src="https://user-images.githubusercontent.com/24245590/40478435-5422308a-5f49-11e8-9488-d67b70bc6011.png">

**Comment by Charlie-Hua** [comment]
Hi @Lineakat, I found the solution to turn Remote Debugger back on in [this comment](https://github.com/expo/expo/issues/1210#issuecomment-355352770) in expo/expo#1210

it's as simple as toggling the development mode, reloading JS bundle and refreshing a couple of times.
hope it helps.

**Comment by Lineakat** [comment]
Hi @Charlie-Hua !
I dont know what I did, but at one point (a couple of days later) it just worked again? So I never got to try out your solution, but thanks so much for answering! If it happens again, I will definitely try this :)

**Comment by PiTiLeZarD** [comment]
> Gotcha! I needed to enable debug js remotely on my emulator.Damnit. :P

OMG thanks! How is this not written everywhere?

**Comment by jdhorner** [comment]
I know this issue is closed, and I hate to necro-resurrect something that's almost 7 months old, but it is exactly the problem I'm having, and includes steps I've already taken. First, some background: 

At my company, we deal with credit information, so we have to observe strict PCI compliance rules. One of those rules is that our internal private WiFi still needs to be separated from our wired computers. So I have an in-office-only test phone, with an IP of 10.10.4.25, and my work PC, where I develop with React Native and Expo, at 10.10.8.43. They are not allowed to communicate with each other, unless we specifically open ports between the subnets in our company firewall. 

I've had them open 19000, 19001, and 19002 in order to be able to use Expo and the Metro bundler and debugger. And that all works great. 

But

No matter what I configure, I cannot get the React Devtools section of React-Native-Debugger to "Connect to React" in the lower-left. As a test, I had our IT department temporarily unblock the currently randomized port of `window.__REACT_DEVTOOLS_PORT__`, and finally everything worked great! 

So my problem is that I can't allow React Devtools to use a randomized port for the devtools, but I can't see anywhere to specify a custom port **for that specific purpose**. Do you know where I could specify this port by hand to make `window.__REACT_DEVTOOLS_PORT__` predictable?

**Comment by Naser2** [comment]
On real device:  Shake device & Click "Debug Remote JS". 
On Simulator: Try: Cmd or control + D on the Simulator & Click "Debug Remote JS".

**Comment by egulhan** [comment]
for windows users, you should disable and re-enable Debugging from developer menu and it may show windows firewall popup. after you allow, it should work as expected.
