### ISSUE TITLE
The Android app becomes very slow when connected to the debugger

### ISSUE THREAD

**Issue by THPubs** [jhen0409/react-native-debugger#139]
I'm running my React Native app in a device. The app works smoothly at first. But when I enable remote debugging and connect it to React Native Debugger, the app becomes extremely slow. For example, when I touch a button, it takes about 5 seconds to respond. If the React Native Debugger is off and the default Remote Debugger is opened in the browser, everything works fine same as running without remote debugging. Any idea why this is happening?

React Native Debugger version: 0.7.6
React Native version: 0.47.1
Platform: Android
Is real device of platform: Yes
Operating System: macOS

**Comment by jhen0409** [comment]
I cannot guarantee any connection problems with real devices, you may need to make sure the network is smooth, the date / time for Android device is sync with host machine.

An another problem is if you're enabled the React Inspector, the performance problem of the component updates will be more noticeable (Hide the panel will close the React Inspector server), otherwise should be no difference from the official remote debugger.

**Comment by THPubs** [comment]
@jhen0409 Great thanks for the info! The problem was with `React DevTools`. Simply right clicked and selected `Toggl React DevTools` and the inspector closed. Now the app is working smoothly!

**Comment by pencilcheck** [comment]
Doesn't work for me, the app is just stuck.

**Comment by jhen0409** [comment]
@pencilcheck could you file an new issue and provide more details?

**Comment by pencilcheck** [comment]
What information would you want to see?

**Comment by jhen0409** [comment]
You can see the issue template by click New Issue, even provide an minimal example project will be better, let me reproduce the problem and help you.

**Comment by martsie** [comment]
Are you using Realm by any chance?

**Comment by pencilcheck** [comment]
No, i'm not using realm.
