### ISSUE TITLE
global.reduxNativeDevTools() is undefined

### ISSUE THREAD

**Issue by Foxhoundn** [jhen0409/react-native-debugger#14]
The readme needs a lot work, I've been trying to make this work for hours but no matter how many times I read the instructions, nothing works.

global.reduxNativeDevTools() is undefined.

I have installed React Native Debugger and it says "Waiting, press command-R in simulator..." but obviously nothing happens. Not even the react dev tools load on the bottom of the screen.

I have also failed trying to make this work with the remote.io and with Remote Redux DevTools.

**Comment by zalmoxisus** [comment]
Hey @Foxhoundn,

[Here's a detailed guide](https://medium.com/react-native-development/develop-react-native-redux-applications-like-a-boss-with-this-tool-ec84bed7af8#.6166au4ic) you can follow.

If you can amend the README it would be more than welcome. If you need help with making a PR let me know. It's an opensource project which evolves with the help of any contributors.

@jhen0409, maybe we better point to `remote-redux-devtools` instead of `global.reduxNativeDevTools` to avoid confusions. The latter is still good to keep as an option. Also we have `mobx-remotedev` which should work just fine here, and hope there will be more iimplementations in the future.

**Comment by jhen0409** [comment]
@zalmoxisus, for `global.reduxNativeDevTools`, I just want let experience like [extension](https://github.com/zalmoxisus/redux-devtools-extension), so I make it send message by worker (although it a bit hacky lol).

I'll consider support `remote-redux-devtools`, but I hope to have a not set `host`, `port` approach.
