### ISSUE TITLE
[FEATURE] Debug network requests

### ISSUE THREAD

**Issue by DenJohX** [jhen0409/react-native-debugger#15]
That would be really useful.

Could something like this be implemented? [http://stackoverflow.com/questions/33997443/how-can-i-view-network-requests-for-debugging-in-react-native](http://stackoverflow.com/questions/33997443/how-can-i-view-network-requests-for-debugging-in-react-native)

Cheers.

**Comment by jhen0409** [comment]
Hey @DenJohX, thanks for feature request! :)

> Could something like this be implemented? http://stackoverflow.com/questions/33997443/how-can-i-view-network-requests-for-debugging-in-react-native

[That answer](http://stackoverflow.com/questions/33997443/how-can-i-view-network-requests-for-debugging-in-react-native/38063958#38063958) should be work directly on RNDebugger, because it will replace Native request by browser request, and it no problems of cross origin requests for Electron, but I think it will break `NSExceptionDomains` for iOS, in order to avoid confusion, I'm considering it as an option for RNDebugger or just add to the Debugger tips of readme.

**Comment by martinezguillaume** [comment]
I have these two errors when use this trick
```js
fetch.js:459 Refused to set unsafe header "connection"(anonymous function)
fetch.js:459 Refused to set unsafe header "proxy-connection"
```

**Comment by jhen0409** [comment]
This feature have been included in context menu (right-click) and macOS Touch Bar, see [`Debugger Integration`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/debugger-integration.md) section of docs.

Feel free to open new issue / PR if you have any problems that not mentioned in the documentation.
