### ISSUE TITLE
UI don't work anymore in Ubuntu 16.04

### ISSUE THREAD

**Issue by th0m4sb** [jhen0409/react-native-debugger#163]
Hello,

The debugger doesn't work anymore in ubuntu 16.04 full up-to-date. I can only see the app icon.
![capture du 2017-10-17 22-52-17](https://user-images.githubusercontent.com/22387986/31689257-241ba2f6-b38f-11e7-98bc-69765e73a68f.png)

The process is running but i don't have the UI.
![capture du 2017-10-17 22-55-16](https://user-images.githubusercontent.com/22387986/31689140-cbc25df2-b38e-11e7-8d2e-991f3728d28e.png)

I try to build from source but there is same problem.

React Native Debugger app version: ALL
Operating System: Ubuntu 16.04

**Comment by jhen0409** [comment]
It's fixed in https://github.com/jhen0409/react-native-debugger/commit/f31e1a68fa29f4f28c871fd900ccdb2eeb6a439c , but due to it saved the wrong window bounds, it just show zero size of window.

Also I added https://github.com/jhen0409/react-native-debugger/commit/fada72ad2d62cee372442a9bdeb7bb0625da21ea, these should release at today.

**Comment by jhen0409** [comment]
Fixed in [`v0.7.12`](https://github.com/jhen0409/react-native-debugger/releases/tag/v0.7.12).

**Comment by th0m4sb** [comment]
It's works again, thank you.
