### ISSUE TITLE
Debugger not working with Android build (expo detached app)

### ISSUE THREAD

**Issue by pencilcheck** [jhen0409/react-native-debugger#175]
Reference: https://github.com/jhen0409/react-native-debugger/issues/139#issuecomment-338369162

I don't know why but the app seems to be unresponsive after launching the debugger next to it.
On a related note, I noticed it slows down iOS a lot when the debugger is on but it is still usable, but for Android it is simply not usable. Also no logs and nothing shows up in the debugger for Android.

React Native Debugger app version: 0.7.12
React Native version: expo detached - 0.48
Platform: Android
Is real device of platform: No
Operating System: macOS 10.13

**Comment by xavier-villelegier** [comment]
Same here with a detached app.
The simulator himself works (I can access the notification center via the status bar smoothly) but the app doesn't respond. It does API request, but touches don't do anything. Works on iOS though.

I tried to toggle DevTools, Redux Tools, Developer Tools, nothing works, even with those 3 all deactivated.

React Native Debugger app version: 0.7.12
React Native version: Expo SDK 21 (React Native 0.48)
Platform: Android
Is real device of platform: No (Nexus 5X simulator)
Operating System: macOS 10.13 High Sierra

**Comment by jhen0409** [comment]
I was tried bootstrap project by with [xde](https://github.com/expo/xde) and detached, it very slow by just use standard remote debugger (debugger-ui), so I think the problem is not directly related to RNDebugger, not sure if it same with you, I'll investigate this more when I have time.

**Comment by calanti** [comment]
Any more news on this? I just detached and having similar issues on Android (can't test iOS, using WIndows) The app takes a good 3-4 minutes to full load when opened (packager running in XDE), and changes to the code take a few minutes to update on the device. It's simply not possible to use this as it is. I had to detach because we need to integrate OneSignal. I have to use XDE because of a CORS issue on chrome debugger, I tried following some fixes for this but I was unsuccessful.

Expo: 24.0.0 (has other issues with 25.0.0 so had to roll back)
RN: 24.0.0 fork
React: 16.0.0
exp: 5.6.0
XDE: 2.22.1.0

**Comment by pencilcheck** [comment]
I found out how to make it faster, use the lan option instead of the tunnel option, and the debugger will start working at semi-normal speed.

**Comment by calanti** [comment]
I can confirm that setting host to LAN has fixed my speed issue, loading and reloading is almost instantaneous, thank you!

![exp settings](https://user-images.githubusercontent.com/12170223/36930735-8e21d0bc-1ee2-11e8-8292-f04ff1e0f13c.png)
