### ISSUE TITLE
Not showing source code in source tab

### ISSUE THREAD

**Issue by mojodev** [jhen0409/react-native-debugger#228]
I just installed react native debugger on my mac. other thing working fine but source code of app in source tab not showing.

<img width="1440" alt="screen shot 2018-04-29 at 10 22 36 am" src="https://user-images.githubusercontent.com/16475786/39403355-acde262c-4b97-11e8-9fe8-b2ffc3263ed4.png">

**Comment by jhen0409** [comment]
It may related to https://github.com/facebook/react-native/issues/18416, but I don't know if you're on Android. Please provide more info by use the issue template.

**Comment by theideasaler** [comment]
I met the same issue. 
![Uploading reactnativedebugger.JPG…]()

the code used to connect my store to react native debugger is showed below:
`import { createStore, combineReducers, compose } from 'redux';

import placesReducer from './reducers/places';

const rootReducer = combineReducers({
    places: placesReducer
});

let composeEnhancers = compose;

if(__DEV__){
    composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
};

const configureStore = () => {
    return createStore(rootReducer,composeEnhancers());
};

export default configureStore;`

**Comment by mojodev** [comment]
@jhen0409 i am using android emulator and also source code is not showing in Chrome Developer Tools.

**Comment by juanlet** [comment]
I-m having the same issue, same code as @theideaSaler

**Comment by jhen0409** [comment]
I have the same issue sometimes and I can solve that by followed https://github.com/facebook/react-native/issues/18416#issuecomment-378985119. (`react-native start --reset-cache`)

It looks like upstream issue, please subscribe https://github.com/facebook/react-native/issues/18416 as well.

**Comment by jwnewman12** [comment]
I had this issue as well with RN 0.54. It would connect fine, redux devtools worked, but my source files would not appear under localhost:8081.  One thing that usually worked was stopping and restarting the metro packager, then just reloading the app.

Since moving to RN 0.56 that is gone, localhost:8081 appears everytime in the source listing right after connecting.

[Now though, I am facing a different issue with 0.56 where the android emulator does not respond to most touch events only when connected in the debugger .. hopefully I can get through that.  Not debugging or on the physical device is fine.  Attach to the debugger, buttons etc do not work.  ?]

**Comment by TRIPTI-JAIN** [comment]
Restart your metro bundler
**react-native start --reset-cache**
