### ISSUE TITLE
Missing refresh and toggle element buttons in touch bar

### ISSUE THREAD

**Issue by sambegin** [jhen0409/react-native-debugger#368]
Any reason why we would be missing those two (important) buttons? I can't find a way to get them displayed on the mac touch bar : 

<img width="1085" alt="Touch Bar Shot 2019-07-12 at 10 01 47 AM" src="https://user-images.githubusercontent.com/6645382/61133918-65189f80-a48c-11e9-9114-14ca400ab1f3.png">

It disappeared like two weeks ago... Thank you! 

React Native Debugger app version: 0.9.10
React Native version: 0.59.6
Platform: iOS and Android
Is real device of platform: Yes
Operating System:  macOS

**Comment by jhen0409** [comment]
For Android, you should install the additional package:

```bash
$ yarn add react-native-devsettings-android
$ react-native link react-native-devsettings-android
```

See [`docs/shortcut-references.md`](https://github.com/jhen0409/react-native-debugger/blob/master/docs/shortcut-references.md#android-support-for-ios-only-features).

It should be work by default on iOS.

Also, if you are not using dev bundle (`--dev false`), it is expected, because we can't get the dev methods.
