### ISSUE TITLE
Touch events are blocked when RNDebugger is on!

### ISSUE THREAD

**Issue by abdulghanitech** [jhen0409/react-native-debugger#536]
React Native Debugger app version: [0.11.3]
React Native version: [0.62.2]
Platform: [Android]
Is real device of platform: [Yes]
Operating System: [Windows]

I'm not able to click on buttons or use react-navigation or fire click events when RNDebugger is turned on.
As per someone's suggestion I've checked both my device's and system's time they're the same. But the problem is still there. 
And I don't know why #438 was closed, apparently, it's still there.

**Comment by jhen0409** [comment]
> And I don't know why #438 was closed, apparently, it's still there.

The issue is closed based on the problem and solution that I can confirm, so it's free to open a new issue if they still get the same problem. (you did 👍)

I tried to reproduce it using `expo init --template expo-template-tabs` (that template included react-navigation v5), but it works normally.

It would be helpful if you can provide possible reproduce steps or example project.

**Comment by rennard** [comment]
+1

**Comment by jhen0409** [comment]
OK, we should follow https://github.com/facebook/react-native/issues/28687 for issue about Android. It's not caused by this debugger app.
