### ISSUE TITLE
Apollo Client DevTools integration

### ISSUE THREAD

**Issue by blackxored** [jhen0409/react-native-debugger#61]
Would it be possible to add [Apollo devtools](https://github.com/apollographql/apollo-client-devtools) to a build? This would come really handy when debugging GraphQL.

**Comment by jhen0409** [comment]
I just saw https://github.com/apollographql/apollo-client-devtools/issues/6, I'll consider to take time for investigate it.

**Comment by faceyspacey** [comment]
@jhen0409 any luck with the apollo devtools?

**Comment by thebigredgeek** [comment]
Any luck?

**Comment by faceyspacey** [comment]
@jhen0409 just left a note regarding this for you on the corresponding Apollo Issue:

https://github.com/apollographql/apollo-client-devtools/issues/6#issuecomment-305886602

I know Apollo you likely view as less popular than plain Redux, but by incorporating this you basically bring every Apollo + React Native user to your devtools environment. It's really a major missing thing for the Apollo community. I also think having this in your debugger will do a lot to further the graphql movement. To me, it's a crime--because GraphQL shines even better on mobile than on web. These days I'm building my web apps simpler and my native apps with far more features. I far prefer developing in React Native than for web. And I'm not alone. It's the more important market, and it also now has better more seamless tooling thanks to the React Native ecosystem. So because GraphQL (and Apollo usage) is likely to be far more advanced in React Native it's even more important that the Apollo Devtools are there. The apollo client and related tools are quiet heavy. I don't even like to ship them to web apps. I make my web apps simple enough to just use regular ajax requests. But React Native is all about Apollo. I'm likely not alone. Apollo really shines in native mobile apps. That's why--in one way or another--this needs to happen.

**Comment by jhen0409** [comment]
Ideally, I think the followup works might be just these steps if we want to make it into RNDebugger:

1. Replace [`evalInPage`](https://github.com/apollographql/apollo-client-devtools/blob/master/app/evalInPage.js) with a function that able to run code in the debugger worker
1. Use `worker.addEventListener('message', ...)` instead of [the listening event of background script](https://github.com/apollographql/apollo-client-devtools/blob/e204337b594e50f1804131fd988e37f8bc8aea7a/extension/background.js#L2) (like [this](https://github.com/jhen0409/react-native-debugger/blob/master/app/middlewares/reduxAPI.js#L55))
1. Add [`the hook`](https://github.com/apollographql/apollo-client-devtools/blob/master/extension/hook.js#L5) into debugger worker.
1. Re-use `apollo-client-devtools` components, maybe just `npm install apollographql/apollo-client-devtools`
1. Finally, consider the implementation of the layout

Just reading the code a bit, but not sure when to do it, so I added `help wanted` tag first. :)

**Comment by larryranches** [comment]
Also interested about this. Since react-native-debugger is the go to debugging tool imo especially if your using redux. Would be ideal if Apollo devtools and this module could work together.

**Comment by larryranches** [comment]
Any update on this? @jhen0409

**Comment by jhen0409** [comment]
I started using Apollo, maybe I'll start work on this at this month. :)

**Comment by faceyspacey** [comment]
That is super exciting!!

**Comment by larryranches** [comment]
@jhen0409 Yes this is great news! How can we help?

**Comment by jhen0409** [comment]
In addition to https://github.com/jhen0409/react-native-debugger/issues/61#issuecomment-305982790, we may need to upgrade `remotedev-app` to v0.11 (current beta) first because it have custom tabs UI, I probably will make Apollo Client DevTools as a tab with Redux DevTools together.

**Comment by faceyspacey** [comment]
That's a very good idea

**Comment by larryranches** [comment]
@jhen0409 Any update on this feature?

**Comment by farzd** [comment]
excited about this too

**Comment by larryranches** [comment]
Right now, I am using this tool to debug apollo with a custom redux store. You can use this tool to view the Apollo store and view any of its actions that it makes when calling a query or mutation. 

It doesn't have the full feature rich tooling set like https://github.com/apollographql/apollo-client-devtools has but its better then nothing.

@jhen0409 If we had this full tooling of apollo-client-devtools along with this package (react-native-debugger), it would literally be the greatest thing ever for us React Native devs using Apollo!

**Comment by jhen0409** [comment]
Move to #177. 🎉
