### ISSUE TITLE
The provided value 'blob' is unsupported in this environment

### ISSUE THREAD

**Issue by tlvince** [jhen0409/react-native-debugger#62]
When using [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) and debugging with react-native-debugger, as soon as `fetch` is called, the app throws `The provided value ‘blob’ is unsupported in this environment`. This does not happen using standard Chrome dev tools or when using RN's built in fetch polyfill.

```
Error: The provided value 'blob' is unsupported in this environment.
    at invariant (invariant.js:44)
    at XMLHttpRequest.set (XMLHttpRequest.js:190)
    at fetch.js:455
    at tryCallTwo (core.js:45)
    at doResolve (core.js:200)
    at new Promise (core.js:66)
    at self.fetch (fetch.js:425)
    at haveUser (auth.js:142)
    at login (auth.js:201)
    at Object.dispatch (index.js:11)
```

react-native-debugger: 0.6.3
React Native version: 0.42
Platform: Android
Is real device of platform: Yes
Operating System: Linux

**Comment by jhen0409** [comment]
Due to #56 I removed native `Blob` in web worker, and actually RN is not supported Blob, I think the error will also thrown in non-debug mode. Let me know If it's not.

For fetch-blob I think it should have polyfill to do, instead of the error from [this line of react-native](https://github.com/facebook/react-native/blob/454ab8fc238da16f9c3986d9a64ea8e716ac0bac/Libraries/Network/XMLHttpRequest.js#L195).

**Comment by jhen0409** [comment]
I think https://github.com/wkh237/react-native-fetch-blob/issues/323#issuecomment-294299914 explained, the same as my comment on the above.
