### ISSUE TITLE
Expo SDK48 Debugging

### ISSUE THREAD

**Issue by poinch** [jhen0409/react-native-debugger#754]
React Native Debugger app version: v0.13.0 latest
React Native version: 0.69.6
Platform: Android
Is real device of platform: No
Operating System: Windows

I'm wondering why after the update to Expo SDK48 with hermes engine i'm not able to debug the cose anymore using RND.
It's someone working on it?

**Comment by NBROKN** [comment]
I had the same issue and for other reasons i went with a dev build, and since i had sdk48, remote debugger was not an option, i tried to downgrade to sdk47, then the reanimated library didn't work and i read in expo doc that even if it did, it wont work with remote debugger. Since i needed that reanimated library, i went back to sdk48 and for some reason, now i have remote debugger option in app dev menu and just confirmed that react native debugger fully works.

That's my 2cents that i still cant make sense of.

**Comment by poinch** [comment]
So maybe I should update from 46 to 47 and then 48! I’ll try

**Comment by mononoke-choi** [comment]
after upgrading to sdk 48 or initializing expo 48 app by `yarn create expo-app --template blank@beta`, i can't use rndebugger..!

**Comment by knighthedspi** [comment]
me either, I cannot use `remote debugging` mode anymore.

**Comment by cdlarson91** [comment]
Same. Worked fine with Expo SDK 46 but now remote debugging does not appear available in SDK 48, so I can't figure out how to use React Native Debugger.

**Comment by cdlarson91** [comment]
Seems to be a known and intentional action per the Expo docs. See the following: 

https://docs.expo.dev/guides/using-hermes/#can-i-use-remote-debugging-with-hermes

which says, _"Hermes supports Chrome DevTools Protocol to debug JavaScript in place by connecting to the running engine on the device. This enables you to debug your app even when using JSI modules. This debugging technique is superior to remote debugging and replaces it for apps using Hermes."_

The link above includes information for a workaround (i.e. switching away from the Hermes engine).

**Comment by about-coding** [comment]
Same for me. After upgrading to 48 SDK RND didn't work anymore.

I managed to run it again for iOS by adding following config to my app.json:

`    
"jsEngine": "hermes",
"ios": {
      "jsEngine": "jsc",
      "supportsTablet": true
    },
`

Important: 
Then start your app with `npx expo start --localhost`. It only worked after adding the --locahost flag

**Comment by poinch** [comment]
I can confirm that adding "jsEngine": "jsc" in the app.json under "android" and "ios" RND will start working again.
If doesn't work at first, just relaunch the project shake your device and click the OPEN JS DEBUGGER

**Comment by aleksandarbos** [comment]
when switching to `jsc` engine, i get:

```No compatible apps connected. JavaScript Debugging can only be used with the Hermes engine. Learn more: https://docs.expo.dev/guides/using-hermes/```

**Comment by Bohdan100** [comment]
I also solved my problem by adding:  "jsEngine": "hermes", "ios": { "jsEngine": "jsc", "supportsTablet": true }, + expo start --localhost
As it stated in this conversation above, thanks.

**Comment by HughBerryman** [comment]
doesn't work for me sadly. open js debugger option disappears when I update the app.json to the above recs

**Comment by reidgarner** [comment]
> doesn't work for me sadly. open js debugger option disappears when I update the app.json to the above recs

Same

**Comment by ser-emejia** [comment]
> doesn't work for me sadly. open js debugger option disappears when I update the app.json to the above recs

Same here, any solutions?

**Comment by aleksandarbos** [comment]
It looks like the expo is shifting away from jsc

> Remote debugging for JSC is disabled in Expo Go and expo-dev-client. JSC remote debugging never worked particularly well compared to debugging with Hermes, and it has become unreliable over time. For more context, [refer to this pull request to React Native](https://github.com/facebook/react-native/pull/36754#pullrequestreview-1400288340), which will be included in their next release

src https://blog.expo.dev/expo-sdk-49-c6d398cdf740

**Comment by saintyoseph** [comment]
> Same for me. After upgrading to 48 SDK RND didn't work anymore.
> 
> I managed to run it again for iOS by adding following config to my app.json:
> 
> ```
> "jsEngine": "hermes",
> "ios": {
>    "jsEngine": "jsc",
>    "supportsTablet": true
> },
> ```
> 
> **Important:** Then start your app with `npx expo start --localhost`. It only worked after adding the --localhost flag

i did the same but it gives an arror like down below:
`No apps connected. Sending "devMenu" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.`
