### ISSUE TITLE
global.reduxNativeDevTools is undefined

### ISSUE THREAD

**Issue by GeoffreyPlitt** [jhen0409/react-native-debugger#8]
Hi,

I followed all of the instructions, and installed everything, but my React app is still opening the old/normal debugger window into Chrome.

I also notice that if I just run Node and look at global.reduxNativeDevTools, it's undefined.

What has to run to inject this into globals?

**Comment by GeoffreyPlitt** [comment]
Update: It DOES work if I open http://remotedev.io/local/ first. Is that expected?

**Comment by jhen0409** [comment]
The `global.reduxNativeDevTools` is inject by [debuggerWorker.js](https://github.com/jhen0409/react-native-debugger/blob/master/app/containers/Debugger/debuggerWorker.js#L16), so you should ensure you're debugging with RNDebugger app, not in Chrome.

If you're using [react-native-debugger-open](https://github.com/jhen0409/react-native-debugger/tree/master/patch), make sure you're opened the app before (registered URI scheme), otherwise it will still open debugger-ui for Chrome. If you're not using [react-native-debugger-open](https://github.com/jhen0409/react-native-debugger/tree/master/patch), or Linux / Windows platforms, please keep the app running, and ensure all debugger-ui for Chrome are closed. (I also wrote in [README of react-native-debugger-open](https://github.com/jhen0409/react-native-debugger/tree/master/patch#react-native-debugger-open))

> Update: It DOES work if I open http://remotedev.io/local/ first. Is that expected?

No. :\
